cz.MyAppName=Databázový server Firebird %1
cz.ServerInstall=Plná instalace serveru a vývojových nástrojů.
cz.SuperServerInstall=Plná instalace Super serveru a vývojových nástrojů.
cz.ClassicServerInstall=Plná instalace Classic serveru a vývojových nástrojů.
cz.DeveloperInstall=Instalace klientských nástrojů pro vývojáře a databázové administrátory.
cz.ClientInstall=Minimální klientská instalace - bez serveru či nástrojů.
cz.CustomInstall=Uživatelská instalace
cz.SuperServerComponent=Super server binárka
cz.ClassicServerComponent=Classic server binárka
cz.ServerComponent=Serverové součásti
cz.DevAdminComponent=Nástroje pro vývoj a správu
cz.ClientComponent=Klientské součásti
cz.UseGuardianTask=Použít &Hlídače pro řízení serveru?
cz.UseApplicationTaskMsg=Spouštět jako &Aplikaci?
cz.TaskGroupDescription=Spouštět Firebird server jako:
cz.UseServiceTask=Spouštět jako &Službu?
cz.AutoStartTask=Spustit &Firebird automaticky při startu systému?
cz.SuperClassicTask=Použít SuperClassic?
cz.CopyFbClientToSysTask=Kopírovat Firebird &klientskou knihovnu do složky <system>?
cz.CopyFbClientAsGds32Task=Vytvořit klientskou knihovnu GDS32.DLL pro podporu &starších aplikací?
cz.InstallCPLAppletTask=Nainstalovat ovladač do Ocládacích &Panelů?
cz.instreg=Aktualizování registrů
cz.instclientCopyFbClient=Kopírování fbclient do složky <sys>
cz.instclientGenGds32=Vytváření gds32.dll do složky <sys>
cz.instclientDecLibCountGds32=Snížení čítače a případné odstranění sdílené knihovny pro gds32.
cz.instclientDecLibCountFbClient=Snížení čítače a případné odstranění sdílené knihovny pro fbclient.
cz.instsvcSetup=Nastavování služby
cz.instsvcStartQuestion=Spustit službu Firebird nyní?
cz.instsvcStartMsg=Spouštění služby serveru
cz.instsvcStopMsg=Zastavování služby
cz.instsvcRemove=Odstraňování služby
cz.instappStartQuestion=Spustit Firebird nyní?
cz.instappStartMsg=Spouštění aplikace serveru

cz.InstallSummarySuffix1=Tato verze Firebirdu se stane výchoz instalací.
cz.InstallSummarySuffix2=Pamatujte, že instalování této verze Firebirdu,
cz.InstallSummarySuffix3=   když je již nainstalována verze novější,
cz.InstallSummarySuffix4=      může mít nepředvídatelné výsledky.

cz.InstallSummaryCancel1= Pokud budete v této instalaci pokračovat, Firebird bude nainstalován, ale nebude nastaven.
cz.InstallSummaryCancel2= Instalaci budete muset dokončit ručně.
cz.InstallSummaryCancel3= Chcete přerušit tuto instalaci?

cz.InstalledProducts=Předinstalační kontrola nalezla existujicí Firebird %s či Interbase %s.
cz.InstalledProdCountSingular=verze
cz.InstalledProdCountPlural=verzí

cz.FbRunning1=Stávající Firebird %s server je spuštěný.
cz.FbRunning2=  Dříve, než budete pokračovat, musíte
cz.FbRunning3=       ukončit program či službu.

cz.PreviousInstallBroken=   (Z důvodu chybného označení verze, se instalace zdá být poškozena.)
cz.PreviousInstallGood=   (Instalace se zdá být v pořádku.)

cz.IconReadme=Firebird %1 čti mě
cz.IconUninstall=Odinstalovat Firebird %1
cz.ReleaseNotes= poznámky k vydání. (Vyžaduje Acrobat Reader.)
cz.InstallationGuide= návod k instalaci. (Vyžaduje Acrobat Reader.)
cz.BugFixes= opravené chyby. (Vyžaduje Acrobat Reader.)
cz.Uninstall=Odinstalovat Firebird %1
cz.Winsock2Web1=Není nainstalovaný Winsock 2.
cz.Winsock2Web2=Chcete navštívit domovskou stránku aktualizace Winsock 2?
cz.NoWinsock2=Než budete pokračovat, nainstalujte prosím aktualizaci Winsock 2.
cz.MSWinsock2Update=http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

cz.RunCSNoGuardian=Spustit Firebird Classic server (bez hlídače)
cz.RunSSNoGuardian=Spustit Firebird Super server (bez hlídače)
cz.RunSSWithGuardian=Spustit Firebird Super server (s hlídačem)
cz.RunCSWithGuardian=Spustit Firebird Classic server (s hlídačem)
cz.RunISQL=Spustit interaktivní SQL nástroj založený na příkazové řádce

cz.ReadmeFile=ctime.txt
cz.InstallationReadmeFile=instalace_ctime.txt
cz.IncompleteTranslationNotice=Tento dokument není aktuální. Pro poslední informace, prosím, nahlédněte do originální anglické dokumentace.
cz.RunCS=Spustit Firebird v módu Classic server
cz.RunSC=Spustit Firebird v módu SuperClassic server
cz.RunSS=Spustit Firebird v módu SuperServer

cz.ServerTaskDescription=Zvolte architekturu serveru:
cz.initSecurityDb=Přidat SYSDBA do bezpečnostní databáze.
cz.SYSDBAPasswordMismatch=Zadané heslo nesouhlasí. Zadejte prosím heslo pro SYSDBA znovu.
cz.SYSDBAPasswordEmpty=Není zadané heslo. Heslo pro SYSDBA musíte zadat.
cz.EnableLegacyClientAuth=Povolit &ověření starších klientů Firebirdu?
cz.CreateSYSDBAPassword=Vytvořit heslo pro systémového správce databáze
cz.ClickThroughPWCreation=Nebo klepněte pro použití výchozího hesla masterkey.
cz.PasswordNote=*** Pozor - ve Firebirdu 3 jsou masterkey a masterke dvě odlišná hesla. ***
cz.SYSDBAPassword=Heslo pro SYSDBA:
cz.RetypeSYSDBAPassword=Znovu heslo pro SYSDBA:
cz.InstallingMSVC32runtimes=Instaluji 32bitové běhové knihovny MSVC do systémové složky
cz.InstallingMSVC64runtimes=Instaluji 64bitové běhové knihovny MSVC do systémové složky

