/*
 *  The contents of this file are subject to the Initial
 *  Developer's Public License Version 1.0 (the "License");
 *  you may not use this file except in compliance with the
 *  License. You may obtain a copy of the License at
 *  http://www.ibphoenix.com/main.nfs?a=ibphoenix&page=ibp_idpl.
 *
 *  Software distributed under the License is distributed AS IS,
 *  WITHOUT WARRANTY OF ANY KIND, either express or implied.
 *  See the License for the specific language governing rights
 *  and limitations under the License.
 *
 *  The Original Code was created by Mark O'Donohue
 *  for the Firebird Open Source RDBMS project.
 *
 *  Copyright (c) 2002 Mark O'Donohue <skywalker@users.sourceforge.net>
 *  and all contributors signed below.
 *
 *  All Rights Reserved.
 *  Contributor(s): ______________________________________.
 *
 *  2005.05.19 Claudio Valderrama: signal tokens that aren't reserved in the
 *      engine thanks to special handling.
 *  Adriano dos Santos Fernandes
 */

#include "firebird.h"

#ifdef HAVE_STRING_H
#include <string.h>
#endif

#define _yacc_defines_yystype
#include "gen/parse.h"
#include "keywords.h"

// CVC: The latest column indicates whether the token has special handling in
// the parser. If it does, KEYWORD_stringIsAToken will return false.
// I discovered isql was being fooled and put double quotes around those
// special cases unnecessarily.

static const TOK tokens[] =
{
	{NOT_LSS, "!<", false},
	{NEQ, "!=", false},
	{NOT_GTR, "!>", false},
	{'(', "(", false},
	{')', ")", false},
	{',', ",", false},
	{'<', "<", false},
	{LEQ, "<=", false},
	{NEQ, "<>", false},	// Alias of !=
	{'=', "=", false},
	{'>', ">", false},
	{GEQ, ">=", false},
	{BIND_PARAM, ":=", false},
	{ABS, "ABS", false},
	{KW_ABSOLUTE, "ABSOLUTE", true},
	{ACCENT, "ACCENT", true},
	{ACOS, "ACOS", false},
	{ACOSH, "ACOSH", false},
	{ACTION, "ACTION", true},
	{ACTIVE, "ACTIVE", false},
	{ADD, "ADD", false},
	{ADMIN, "ADMIN", false},
	{AFTER, "AFTER", false},
	{ALL, "ALL", false},
	{ALTER, "ALTER", false},
	{ALWAYS, "ALWAYS", true},
	{AND, "AND", false},
	{ANY, "ANY", false},
	{AS, "AS", false},
	{ASC, "ASC", false},	// Alias of ASCENDING
	{ASC, "ASCENDING", false},
	{ASCII_CHAR, "ASCII_CHAR", false},
	{ASCII_VAL, "ASCII_VAL", false},
	{ASIN, "ASIN", false},
	{ASINH, "ASINH", false},
	{AT, "AT", false},
	{ATAN, "ATAN", false},
	{ATAN2, "ATAN2", false},
	{ATANH, "ATANH", false},
	{AUTO, "AUTO", false},
	{AUTONOMOUS, "AUTONOMOUS", false},
	{AVG, "AVG", false},
	{BACKUP, "BACKUP", true},
	{BEFORE, "BEFORE", false},
	{BEGIN, "BEGIN", false},
	{BETWEEN, "BETWEEN", false},
	{BIGINT, "BIGINT", false},
	{BIN_AND, "BIN_AND", false},
	{BIN_NOT, "BIN_NOT", false},
	{BIN_OR, "BIN_OR", false},
	{BIN_SHL, "BIN_SHL", false},
	{BIN_SHR, "BIN_SHR", false},
	{BIN_XOR, "BIN_XOR", false},
	{BIT_LENGTH, "BIT_LENGTH", false},
	{BLOB, "BLOB", false},
	{BLOCK, "BLOCK", true},
	{BODY, "BODY", true},
	{KW_BOOLEAN, "BOOLEAN", false},
	{BOTH, "BOTH", false},
	{KW_BREAK, "BREAK", true},
	{BY, "BY", false},
	{CALLER, "CALLER", true},
	{CASCADE, "CASCADE", true},
	{CASE, "CASE", false},
	{CAST, "CAST", false},
	{CEIL, "CEIL", false},	// alias of CEILING
	{CEIL, "CEILING", false},
	{KW_CHAR, "CHAR", false},
	{CHAR_LENGTH, "CHAR_LENGTH", false},
	{CHAR_TO_UUID, "CHAR_TO_UUID", false},
	{CHARACTER, "CHARACTER", false},
	{CHARACTER_LENGTH, "CHARACTER_LENGTH", false},
	{CHECK, "CHECK", false},
	{CLOSE, "CLOSE", false},
	{COALESCE, "COALESCE", true},
	{COLLATE, "COLLATE", false},
	{COLLATION, "COLLATION", true},
	{COLUMN, "COLUMN", false},
	{COMMENT, "COMMENT", true},
	{COMMIT, "COMMIT", false},
	{COMMITTED, "COMMITTED", false},
	{COMMON, "COMMON", true},
	{COMPUTED, "COMPUTED", false},
	{CONDITIONAL, "CONDITIONAL", false},
	{CONNECT, "CONNECT", false},
	{CONSTRAINT, "CONSTRAINT", false},
	{CONTAINING, "CONTAINING", false},
	{CONTINUE, "CONTINUE", true},
	{CORR, "CORR", false},
	{COS, "COS", false},
	{COSH, "COSH", false},
	{COT, "COT", false},
	{COUNT, "COUNT", false},
	{COVAR_POP, "COVAR_POP", false},
	{COVAR_SAMP, "COVAR_SAMP", false},
	{CREATE, "CREATE", false},
	{CROSS, "CROSS", false},
	{CSTRING, "CSTRING", false},
	{CUME_DIST, "CUME_DIST", false},
	{CURRENT, "CURRENT", false},
	{CURRENT_CONNECTION, "CURRENT_CONNECTION", false},
	{CURRENT_DATE, "CURRENT_DATE", false},
	{CURRENT_ROLE, "CURRENT_ROLE", false},
	{CURRENT_TIME, "CURRENT_TIME", false},
	{CURRENT_TIMESTAMP, "CURRENT_TIMESTAMP", false},
	{CURRENT_TRANSACTION, "CURRENT_TRANSACTION", false},
	{CURRENT_USER, "CURRENT_USER", false},
	{CURSOR, "CURSOR", false},
	{DATABASE, "DATABASE", false},
	{DATA, "DATA", true},
	{DATE, "DATE", false},
	{DATEADD, "DATEADD", false},
	{DATEDIFF, "DATEDIFF", false},
	{DAY, "DAY", false},
	{DDL, "DDL", false},
	{KW_DEC, "DEC", false},
	{DECIMAL, "DECIMAL", false},
	{DECLARE, "DECLARE", false},
	{DECODE, "DECODE", false},
	{DECRYPT, "DECRYPT", true},
	{DEFAULT, "DEFAULT", false},
	{KW_DELETE, "DELETE", false},
	{DELETING, "DELETING", true},
	{DENSE_RANK, "DENSE_RANK", false},
	{DESC, "DESC", false},	// Alias of DESCENDING
	{DESC, "DESCENDING", false},
	{KW_DESCRIPTOR,	"DESCRIPTOR", true},
	{DETERMINISTIC, "DETERMINISTIC", false},
	{KW_DIFFERENCE, "DIFFERENCE", true},
	{DISCONNECT, "DISCONNECT", false},
	{DISTINCT, "DISTINCT", false},
	{DO, "DO", false},
	{KW_DOMAIN, "DOMAIN", false},
	{KW_DOUBLE, "DOUBLE", false},
	{DROP, "DROP", false},
	{ELSE, "ELSE", false},
	{ENCRYPT, "ENCRYPT", true},
	{END, "END", false},
	{ENGINE, "ENGINE", true},
	{ENTRY_POINT, "ENTRY_POINT", false},
	{ERROR_MESSAGE, "ERROR_MESSAGE", true},
	{ESCAPE, "ESCAPE", false},
	{EXCEPTION, "EXCEPTION", false},
	{EXCLUDE, "EXCLUDE", false},
	{EXECUTE, "EXECUTE", false},
	{EXISTS, "EXISTS", false},
	{EXIT, "EXIT", false},
	{EXP, "EXP", false},
	{EXTERNAL, "EXTERNAL", false},
	{EXTRACT, "EXTRACT", false},
	{KW_FALSE, "FALSE", false},
	{FETCH, "FETCH", false},
	{KW_FILE, "FILE", false},
	{FILTER, "FILTER", false},
	{FIRST, "FIRST", true},
	{FIRST_VALUE, "FIRST_VALUE", false},
	{FIRSTNAME, "FIRSTNAME", false},
	{KW_FLOAT, "FLOAT", false},
	{FLOOR, "FLOOR", false},
	{FOLLOWING, "FOLLOWING", false},
	{FOR, "FOR", false},
	{FOREIGN, "FOREIGN", false},
	{FREE_IT, "FREE_IT", true},
	{FROM, "FROM", false},
	{FULL, "FULL", false},
	{FUNCTION, "FUNCTION", false},
	{GDSCODE, "GDSCODE", false},
	{GENERATED, "GENERATED", true},
	{GENERATOR, "GENERATOR", false},
	{GEN_ID, "GEN_ID", false},
	{GEN_UUID, "GEN_UUID", false},
	{GLOBAL, "GLOBAL", false},
	{GRANT, "GRANT", false},
	{GRANTED, "GRANTED", false},
	{GROUP, "GROUP", false},
	{HASH, "HASH", false},
	{HAVING, "HAVING", false},
	{HOUR, "HOUR", false},
	{IDENTITY, "IDENTITY", false},
	{IF, "IF", false},
	{KW_IGNORE, "IGNORE", true},
	{IIF, "IIF", true},
	{KW_IN, "IN", false},
	{INACTIVE, "INACTIVE", false},
	{INCREMENT, "INCREMENT", false},
	{INDEX, "INDEX", false},
	{INNER, "INNER", false},
	{INPUT_TYPE, "INPUT_TYPE", false},
	{INSENSITIVE, "INSENSITIVE", false},
	{INSERT, "INSERT", false},
	{INSERTING, "INSERTING", true},
	{KW_INT, "INT", false},
	{INTEGER, "INTEGER", false},
	{INTO, "INTO", false},
	{IS, "IS", false},
	{ISOLATION, "ISOLATION", false},
	{JOIN, "JOIN", false},
	{KEY, "KEY", false},
	{LAG, "LAG", false},
	{LAST, "LAST", true},
	{LAST_VALUE, "LAST_VALUE", false},
	{LASTNAME, "LASTNAME", false},
	{LEAD, "LEAD", false},
	{LEADING, "LEADING", false},
	{LEAVE, "LEAVE", true},
	{LEFT, "LEFT", false},
	{LENGTH, "LENGTH", false},
	{LEVEL, "LEVEL", false},
	{LIKE, "LIKE", false},
	{LIMBO, "LIMBO", true},
	{LINGER, "LINGER", true},
	{LIST, "LIST", false},
	{LN, "LN", false},
	{LOCK, "LOCK", true},
	{LOG, "LOG", false},
	{LOG10, "LOG10", false},
	{KW_LONG, "LONG", false},
	{KW_LOWER, "LOWER", false},
	{LPAD, "LPAD", false},
	{MANUAL, "MANUAL", false},
	{MAPPING, "MAPPING", false},
	{MATCHED, "MATCHED", false},
	{MATCHING, "MATCHING", false},
	{MAXIMUM, "MAX", false},
	{MAXVALUE, "MAXVALUE", false},
	{MERGE, "MERGE", false},
	{MILLISECOND, "MILLISECOND", false},
	{MIDDLENAME, "MIDDLENAME", false},
	{MINIMUM, "MIN", false},
	{MINUTE, "MINUTE", false},
	{MINVALUE, "MINVALUE", false},
	{MOD, "MOD", false},
	{MODULE_NAME, "MODULE_NAME", false},
	{MONTH, "MONTH", false},
	{NAME, "NAME", true},
	{NAMES, "NAMES", false},
	{NATIONAL, "NATIONAL", false},
	{NATURAL, "NATURAL", false},
	{NCHAR, "NCHAR", false},
	{NEXT, "NEXT", true},
	{NO, "NO", false},
	{NOT, "NOT", false},
	{NTH_VALUE, "NTH_VALUE", false},
	{NTILE, "NTILE", false},
	{NULLIF, "NULLIF", true},
	{KW_NULL, "NULL", false},
	{NULLS, "NULLS", true},
	{KW_NUMERIC, "NUMERIC", false},
	{OCTET_LENGTH, "OCTET_LENGTH", false},
	{OF, "OF", false},
	{OFFSET, "OFFSET", false},
	{ON, "ON", false},
	{ONLY, "ONLY", false},
	{OPEN, "OPEN", false},
	{OPTION, "OPTION", false},
	{OR, "OR", false},
	{ORDER, "ORDER", false},
	{OS_NAME, "OS_NAME", false},
	{OTHERS, "OTHERS", false},
	{OUTER, "OUTER", false},
	{OUTPUT_TYPE, "OUTPUT_TYPE", false},
	{OVER, "OVER", false},
	{KW_OVERFLOW, "OVERFLOW", false},
	{OVERLAY, "OVERLAY", false},
	{PACKAGE, "PACKAGE", true},
	{PAD, "PAD", true},
	{PAGE, "PAGE", false},
	{PAGES, "PAGES", false},
	{KW_PAGE_SIZE, "PAGE_SIZE", false},
	{PARAMETER, "PARAMETER", false},
	{PARTITION, "PARTITION", false},
	{PASSWORD, "PASSWORD", false},
	{PERCENT_RANK, "PERCENT_RANK", false},
	{PI, "PI", false},
	{PLACING, "PLACING", false},
	{PLAN, "PLAN", false},
	{PLUGIN, "PLUGIN", true},
	{POSITION, "POSITION", false},
	{POST_EVENT, "POST_EVENT", false},
	{POWER, "POWER", false},
	{PRECEDING, "PRECEDING", false},
	{PRECISION, "PRECISION", false},
	{PRESERVE, "PRESERVE", true},
	{PRIMARY, "PRIMARY", false},
	{PRIOR, "PRIOR", true},
	{PRIVILEGE, "PRIVILEGE", false},
	{PRIVILEGES, "PRIVILEGES", false},
	{PROCEDURE, "PROCEDURE", false},
	{PROTECTED, "PROTECTED", false},
	{RAND, "RAND", false},
	{RANGE, "RANGE", false},
	{RANK, "RANK", false},
	{DB_KEY, "RDB$DB_KEY", false},
	{RDB_GET_CONTEXT, "RDB$GET_CONTEXT", true},
	{RDB_RECORD_VERSION, "RDB$RECORD_VERSION", false},
	{RDB_ROLE_IN_USE, "RDB$ROLE_IN_USE", true},
	{RDB_SET_CONTEXT, "RDB$SET_CONTEXT", true},
	{RDB_SYSTEM_PRIVILEGE, "RDB$SYSTEM_PRIVILEGE", true},
	{READ, "READ", false},
	{REAL, "REAL", false},
	{VERSION, "RECORD_VERSION", false},
	{RECREATE, "RECREATE", false},
	{RECURSIVE, "RECURSIVE", false},
	{REFERENCES, "REFERENCES", false},
	{REGR_AVGX, "REGR_AVGX", false},
	{REGR_AVGY, "REGR_AVGY", false},
	{REGR_COUNT, "REGR_COUNT", false},
	{REGR_INTERCEPT, "REGR_INTERCEPT", false},
	{REGR_R2, "REGR_R2", false},
	{REGR_SLOPE, "REGR_SLOPE", false},
	{REGR_SXX, "REGR_SXX", false},
	{REGR_SXY, "REGR_SXY", false},
	{REGR_SYY, "REGR_SYY", false},
	{KW_RELATIVE, "RELATIVE", true},
	{RELEASE, "RELEASE", false},
	{REPLACE, "REPLACE", false},
	{REQUESTS, "REQUESTS", true},
	{RESERVING, "RESERV", false},	// Alias of RESERVING
	{RESERVING, "RESERVING", false},
	{RESTART, "RESTART", true},
	{RESTRICT, "RESTRICT", true},
	{RETAIN, "RETAIN", false},
	{RETURN, "RETURN", false},
	{RETURNING, "RETURNING", true},
	{RETURNING_VALUES, "RETURNING_VALUES", false},
	{RETURNS, "RETURNS", false},
	{REVERSE, "REVERSE", false},
	{REVOKE, "REVOKE", false},
	{RIGHT, "RIGHT", false},
	{ROLE, "ROLE", true},
	{ROLLBACK, "ROLLBACK", false},
	{ROUND, "ROUND", false},
	{ROW, "ROW", false},
	{ROW_COUNT, "ROW_COUNT", false},
	{ROW_NUMBER, "ROW_NUMBER", false},
	{ROWS, "ROWS", false},
	{RPAD, "RPAD", false},
	{SAVEPOINT, "SAVEPOINT", false},
	{SCALAR_ARRAY, "SCALAR_ARRAY", true},
	{DATABASE, "SCHEMA", false},	// Alias of DATABASE
	{SCROLL, "SCROLL", false},
	{SECOND, "SECOND", false},
	{SEGMENT, "SEGMENT", false},
	{SELECT, "SELECT", false},
	{SENSITIVE, "SENSITIVE", false},
	{SEQUENCE, "SEQUENCE", true},
	{SERVERWIDE, "SERVERWIDE", true},
	{SET, "SET", false},
	{SHADOW, "SHADOW", false},
	{KW_SHARED, "SHARED", false},
	{SIGN, "SIGN", false},
	{SIMILAR, "SIMILAR", false},
	{SIN, "SIN", false},
	{SINGULAR, "SINGULAR", false},
	{SINH, "SINH", false},
	{KW_SIZE, "SIZE", false},
	{SKIP, "SKIP", true},
	{SMALLINT, "SMALLINT", false},
	{SNAPSHOT, "SNAPSHOT", false},
	{SOME, "SOME", false},
	{SORT, "SORT", false},
	{SOURCE, "SOURCE", true},
	{SPACE, "SPACE", true},
	{SQLCODE, "SQLCODE", false},
	{SQLSTATE, "SQLSTATE", false},
	{SQRT, "SQRT", false},
	{STABILITY, "STABILITY", false},
	{START, "START", false},
	{STARTING, "STARTING", false},
	{STARTING, "STARTS", false},	// Alias of STARTING
	{STATEMENT, "STATEMENT", true},
	{STATISTICS, "STATISTICS", false},
	{STDDEV_POP, "STDDEV_POP", false},
	{STDDEV_SAMP, "STDDEV_SAMP", false},
	{SUBSTRING,	"SUBSTRING", true},
	{SUB_TYPE, "SUB_TYPE", false},
	{SUM, "SUM", false},
	{SUSPEND, "SUSPEND", false},
	{SYSTEM, "SYSTEM", false},
	{TABLE, "TABLE", false},
	{TAGS, "TAGS", true},
	{TAN, "TAN", false},
	{TANH, "TANH", false},
	{TEMPORARY, "TEMPORARY", true},
	{THEN, "THEN", false},
	{TIES, "TIES", false},
	{TIME, "TIME", false},
	{TIMESTAMP, "TIMESTAMP", false},
	{TIMEOUT, "TIMEOUT", true},
	{TO, "TO", false},
	{TRAILING, "TRAILING", false},
	{TRANSACTION, "TRANSACTION", false},
	{TRIGGER, "TRIGGER", false},
	{TRIM, "TRIM", false},
	{KW_TRUE, "TRUE", false},
	{TRUNC, "TRUNC", false},
	{TRUSTED, "TRUSTED", false},
	{TWO_PHASE, "TWO_PHASE", true},
	{KW_TYPE, "TYPE", true},
	{UNBOUNDED, "UNBOUNDED", false},
	{UNCOMMITTED, "UNCOMMITTED", false},
	{UNDO, "UNDO", true},
	{UNION, "UNION", false},
	{UNIQUE, "UNIQUE", false},
	{UNKNOWN, "UNKNOWN", false},
	{UPDATE, "UPDATE", false},
	{UPDATING, "UPDATING", true},
	{KW_UPPER, "UPPER", false},
	{USAGE, "USAGE", true},
	{USER, "USER", false},
	{USING, "USING", false},
	{UUID_TO_CHAR, "UUID_TO_CHAR", false},
	{KW_VALUE, "VALUE", false},
	{VALUES, "VALUES", false},
	{VAR_POP, "VAR_POP", false},
	{VAR_SAMP, "VAR_SAMP", false},
	{VARCHAR, "VARCHAR", false},
	{VARIABLE, "VARIABLE", false},
	{VARYING, "VARYING", false},
	{VIEW, "VIEW", false},
	{WAIT, "WAIT", false},
	{WEEK, "WEEK", false},
	{WEEKDAY, "WEEKDAY", true},
	{WHEN, "WHEN", false},
	{WHERE, "WHERE", false},
	{WHILE, "WHILE", false},
	{WITH, "WITH", false},
	{WORK, "WORK", false},
	{WRITE, "WRITE", false},
	{YEAR, "YEAR", false},
	{YEARDAY, "YEARDAY", true},
	{NOT_LSS, "^<", false},	// Alias of !<
	{NEQ, "^=", false},				// Alias of !=
	{NOT_GTR, "^>", false},			// Alias of !>
	{CONCATENATE, "||", false},
	{NOT_LSS, "~<", false},	// Alias of !<
	{NEQ, "~=", false},				// Alias of !=
	{NOT_GTR, "~>", false},			// Alias of !>
	{0, NULL, false}
};

// This method is currently used in isql/isql.epp to check if a
// user field is a reserved word, and hence needs to be quoted.
// Obviously a hash table would make this a little quicker.
// MOD 29-June-2002

extern "C" {

int API_ROUTINE KEYWORD_stringIsAToken(const char* in_str)
{
	for (const TOK* tok_ptr = tokens; tok_ptr->tok_string; ++tok_ptr)
	{
		if (!tok_ptr->nonReserved && !strcmp(tok_ptr->tok_string, in_str))
			return true;
	}

	return false;
}

Tokens API_ROUTINE KEYWORD_getTokens()
{
	return tokens;
}

}
