/*
  FILE GENERATED BY src/misc/writeBuildNum.sh
               *** DO NOT EDIT ***
  TO CHANGE ANY INFORMATION IN HERE PLEASE
  EDIT src/misc/writeBuildNum.sh
  FORMAL BUILD NUMBER:2613
*/

#define PRODUCT_VER_STRING "4.0.1.2613"
#define FILE_VER_STRING "WI-V4.0.1.2613"
#define LICENSE_VER_STRING "WI-V4.0.1.2613"
#define FILE_VER_NUMBER 4, 0, 1, 2613
#define FB_MAJOR_VER "4"
#define FB_MINOR_VER "0"
#define FB_REV_NO "1"
#define FB_BUILD_NO "2613"
#define FB_BUILD_TYPE "V"
#define FB_BUILD_SUFFIX "Firebird 4.0"
