/*
  FILE GENERATED BY src/misc/writeBuildNum.sh
               *** DO NOT EDIT ***
  TO CHANGE ANY INFORMATION IN HERE PLEASE
  EDIT src/misc/writeBuildNum.sh
  FORMAL BUILD NUMBER:33033
*/

#define PRODUCT_VER_STRING "3.0.4.33033"
#define FILE_VER_STRING "WI-V3.0.4.33033"
#define LICENSE_VER_STRING "WI-V3.0.4.33033"
#define FILE_VER_NUMBER 3, 0, 4, 33033
#define FB_MAJOR_VER "3"
#define FB_MINOR_VER "0"
#define FB_REV_NO "4"
#define FB_BUILD_NO "33033"
#define FB_BUILD_TYPE "V"
#define FB_BUILD_SUFFIX "Firebird 3.0"
